name: demo_workflow

# when pushed to main branch this workflow activtes
on: 
  push:
  pull_request:

jobs:
  demo-job:
    # this workflow runs in ubuntu
    runs-on: ubuntu-24.04
    steps:
    # this will clone the git repo for us
    - name: checkout code
      uses: actions/checkout@v4
    # this will install yamllint  
    - name: install yamllint
      run: sudo apt-get update && sudo apt-get install -y yamllint
    # thus workflow will pring hello world
    - name: Print hello world
      run: echo "hello world"
